### ISSUE TITLE
Build Error for :: Part 2: The Linux Part > Setup ArchLinux

### ISSUE THREAD

**Issue by joshthemaker** [jrcharney/ArchWSLPlusPlus#7]
After completing the `makepkg -si` I got a make/build error: `error while loading shared libraries: libunistring.so.5: cannot open shared object file: No such file or directory==> ERROR: A failure occurred in build()`

Which I solved by removing the yay folder with  `rm -rf  yay` then I ran `sudo pacman -Su` for a full system upgrade.

next  `cd Downloads`  then
 `git clone https://aur.archlinux.org/yay.git ` 
`cd yay` 
`makepkg -si `  and yay v12.0.2 was installed successfully.

**Comment by jrcharney** [comment]
This really is not an issue because

1. You solved it by upgrading your system and then reinstalling yay.
2. Nothing needs to be done to change the instructions.

Almost all the issues I've received this month have been from people who thought they could use this repository with an older or out-of-date version of Arch Linux.  One guy had a five year old version of Arch Linux and didn't know he was supposed to update the Arch Linux keyring package every few months.

I kinda thought this repo would have attracted more Windows users looking for an alternative to Ubuntu for WSL2.

Regardless, nothing needs to be done.

**Comment by joshthemaker** [comment]
Thanks for the guide btw. I'm just another noob wanting to learn!
